name: Analyze Logs Daily

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas matplotlib requests

      - name: Run Log Analysis
        run: python analyze_logs.py

      - name: Upload Analysis Reports
        uses: actions/upload-artifact@v3
        with:
          name: analysis-reports
          path: "*.png"

      - name: Commit and Push Reports
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b log-analysis || git checkout log-analysis
          git add *.png
          git commit -m "Automated log analysis reports"
          git push origin log-analysis --force
