logo_path: "/home/alfredpi1/Alfred_Emergency_Logo.jpg"
log_dir: "/home/alfredpi1/logs"
status_file: "/home/alfredpi1/pucc_status.txt"
available_color: "#28a745"
unavailable_color: "#dc3545"
auto_unavailable_time: "21:00"
screen_off_time: "22:00"
screen_on_time: "06:00"
fullscreen: true  # Change to false if you want windowed mode
button_color: "#0056b3"  # Choose a color you like, this is a deep blue
